sudo: required
language: scala
dist: trusty
services:
- docker
- docker-engine
- openssl
before_install:
- chmod 775 docker_install.sh
- ./docker_install.sh
- openssl aes-256-cbc -K $encrypted_09d70e6b8d10_key -iv $encrypted_09d70e6b8d10_iv
  -in application.conf.enc -out conf/application.conf -d
- mkdir setup; cd setup
- git clone https://github.com/dro248/setupYvideo.git
- cd setupYvideo
- chmod 775 setup_yvideo.sh
- ./setup_yvideo.sh --test
script:
- cd /home/travis/build/BYU-ODH/Ayamel
- chmod 775 sbt_test_result.sh
- ./sbt_test_result.sh
after_success: 
