sudo: required
language: scala
dist: trusty
services:
- docker
- docker-engine
- openssl
addons:
    apt:
        packages:
            sshpass
before_install:
- chmod 775 docker_install.sh
- ./docker_install.sh
- openssl aes-256-cbc -K $encrypted_09d70e6b8d10_key -iv $encrypted_09d70e6b8d10_iv
  -in application.conf.enc -out conf/application.conf -d
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- export YVIDEO_VERSION=$(if [ "$BRANCH" == "master" ]; then echo "--production"; else echo "--beta"; fi)
- cd ..
- git clone https://github.com/dro248/runAyamel
- cp -r Ayamel runAyamel/test
- cd runAyamel
- chmod 775 setup_yvideo.sh
- ./setup_yvideo.sh --travis
script:
- cd /home/travis/build/BYU-ODH/Ayamel
- chmod 775 sbt_test_result.sh
- ./sbt_test_result.sh
after_success: 
- sshpass -p "$sshpass" $sshuser@$server /var/yvideo/runayamel/setup_yvideo.sh $YVIDEO_VERSION

